<?php 

function djatoka_seadragon_menu() {
  return array(
    'djatoka_test' => array(
      'title' => 'Djatoka Seadragon Testing',
      'access callback' => TRUE,
      'page callback' => 'djatoka_seadragon_callback',
    ),
  );
}

function djatoka_seadragon_theme() {
  return array(
    'djatoka_seadragon_viewer' => array(
      'variables' => array(
        'uri' => '', 
      ),
    ),
  );
}


function djatoka_seadragon_callback() {
  
  
/*   $uri = 'http://localhost:8080/fedora/objects/islandora:313/datastreams/JP2/content'; */
  $uri = 'http://localhost:8080/fedora/objects/islandora:507/datastreams/JP2/content';
/*   $uri = 'http://192.168.56.195/drupal7/islandora/object/islandora:299/datastream/OBJ/view'; */
  
  return theme('djatoka_seadragon_viewer', array('uri' => $uri));
}


//Not sure what we need here yet...  Likely some theme stuff?
function theme_djatoka_seadragon_viewer($vars) {
  // get variables
  $library_path = libraries_get_path('openseadragon');
  $module_path = drupal_get_path('module', 'djatoka_seadragon');

  $viewer_id = 'djatoka-seadragon';
  //XXX:  Requires proxy setup...
  $djatoka_url = "/adore-djatoka/resolver";
  $resource_uri = $vars['uri'];

  //The path to GUI images.
  $image_path = $library_path . '/images';

  // add settings
  drupal_add_js(array('djatoka_seadragon' => array('viewer_id' => $viewer_id, 'djatoka_url' => $djatoka_url, 'resource_uri' => $resource_uri)), 'setting');

  // openseadragon
  drupal_add_js($library_path . '/openseadragon.js');
  // djatoka tilesource
  drupal_add_js($module_path . '/js/djtilesource.js');

  drupal_add_js($module_path . '/js/djatoka_seadragon.js');

  return "<div id='$viewer_id' style='width: 100%; height: 500px; display: block;'/>";
}





/* OpenSeadragon.Config.imagePath = "$image_path/"; */
/* OpenSeadragon.Config.debugMode = true; */

//viewer.addEventListener('open', function(viewer) {alert('open');});
//viewer.addEventListener('error', function(viewer) {alert('error');});
//viewer.addEventListener('ignore', function(viewer) {alert('ignore');});